"""Monthly, yearly and trailing 12 month sensors."""

from __future__ import annotations

from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.const import PERCENTAGE, EntityCategory, UnitOfEnergy

from .. import sensor_values as values
from .base import CURRENCY_UNIT, GivEnergyManagerSensorDescription

DESCRIPTIONS: tuple[GivEnergyManagerSensorDescription, ...] = (
    # ── Monthly accumulations (disabled by default) ───────────────────────────
    GivEnergyManagerSensorDescription(
        key="solar_this_month",
        translation_key="solar_this_month",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        reset_period="month",
        icon="mdi:solar-power",
        entity_registry_enabled_default=True,
        value_fn=lambda d: round(d.month.solar_kwh, 3),
    ),
    GivEnergyManagerSensorDescription(
        key="import_this_month",
        translation_key="import_this_month",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        reset_period="month",
        icon="mdi:transmission-tower-import",
        entity_registry_enabled_default=True,
        value_fn=lambda d: round(d.month.import_kwh, 3),
    ),
    GivEnergyManagerSensorDescription(
        key="export_this_month",
        translation_key="export_this_month",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        reset_period="month",
        icon="mdi:transmission-tower-export",
        entity_registry_enabled_default=True,
        value_fn=lambda d: round(d.month.export_kwh, 3),
    ),
    GivEnergyManagerSensorDescription(
        key="import_cost_this_month",
        translation_key="import_cost_this_month",
        native_unit_of_measurement=CURRENCY_UNIT,
        state_class=SensorStateClass.TOTAL,
        reset_period="month",
        icon="mdi:cash-minus",
        entity_registry_enabled_default=True,
        value_fn=lambda d: round(d.month.total_import_cost, 4),
    ),
    GivEnergyManagerSensorDescription(
        key="export_earnings_this_month",
        translation_key="export_earnings_this_month",
        native_unit_of_measurement=CURRENCY_UNIT,
        state_class=SensorStateClass.TOTAL,
        reset_period="month",
        icon="mdi:cash-plus",
        entity_registry_enabled_default=True,
        value_fn=lambda d: round(d.month.export_earnings, 4),
    ),
    GivEnergyManagerSensorDescription(
        key="export_this_year",
        translation_key="export_this_year",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        reset_period="year",
        entity_registry_enabled_default=False,
        value_fn=lambda d: round(d.year.export_kwh, 3),
    ),
    GivEnergyManagerSensorDescription(
        key="export_earnings_this_year",
        translation_key="export_earnings_this_year",
        native_unit_of_measurement=CURRENCY_UNIT,
        state_class=SensorStateClass.TOTAL,
        reset_period="year",
        entity_registry_enabled_default=False,
        value_fn=lambda d: round(d.year.export_earnings, 4),
    ),
    GivEnergyManagerSensorDescription(
        key="export_trailing_12m",
        translation_key="export_trailing_12m",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=None,
        icon="mdi:transmission-tower-export",
        entity_registry_enabled_default=False,
        value_fn=lambda d: round(d.trailing_12m_export_kwh, 3),
    ),
    GivEnergyManagerSensorDescription(
        key="solar_this_year",
        translation_key="solar_this_year",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        reset_period="year",
        entity_registry_enabled_default=False,
        value_fn=lambda d: round(d.year.solar_kwh, 3),
    ),
    # --- Trailing 12-month sensors (complete billing month history) ---
    GivEnergyManagerSensorDescription(
        key="solar_trailing_12m",
        translation_key="solar_trailing_12m",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=None,
        icon="mdi:solar-power",
        entity_registry_enabled_default=False,
        value_fn=lambda d: round(d.trailing_12m_solar_kwh, 3),
    ),
    GivEnergyManagerSensorDescription(
        key="import_trailing_12m",
        translation_key="import_trailing_12m",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=None,
        icon="mdi:transmission-tower-import",
        entity_registry_enabled_default=False,
        value_fn=lambda d: round(d.trailing_12m_import_kwh, 3),
    ),
    GivEnergyManagerSensorDescription(
        key="import_cost_trailing_12m",
        translation_key="import_cost_trailing_12m",
        native_unit_of_measurement=CURRENCY_UNIT,
        device_class=SensorDeviceClass.MONETARY,
        state_class=None,
        icon="mdi:cash-minus",
        entity_registry_enabled_default=False,
        value_fn=lambda d: round(d.trailing_12m_import_cost, 4),
    ),
    GivEnergyManagerSensorDescription(
        key="export_earnings_trailing_12m",
        translation_key="export_earnings_trailing_12m",
        native_unit_of_measurement=CURRENCY_UNIT,
        device_class=SensorDeviceClass.MONETARY,
        state_class=None,
        icon="mdi:cash-plus",
        entity_registry_enabled_default=False,
        value_fn=lambda d: round(d.trailing_12m_export_earnings, 4),
    ),
    GivEnergyManagerSensorDescription(
        key="import_kwh_cheap_this_month",
        translation_key="import_kwh_cheap_this_month",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        reset_period="month",
        icon="mdi:lightning-bolt-circle",
        entity_registry_enabled_default=True,
        value_fn=lambda d: round(d.month.import_kwh_cheap, 3),
    ),
    GivEnergyManagerSensorDescription(
        key="import_kwh_peak_this_month",
        translation_key="import_kwh_peak_this_month",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        reset_period="month",
        icon="mdi:lightning-bolt",
        entity_registry_enabled_default=True,
        value_fn=lambda d: round(d.month.import_kwh_peak, 3),
    ),
    GivEnergyManagerSensorDescription(
        key="immersion_savings_this_month",
        translation_key="immersion_savings_this_month",
        native_unit_of_measurement=CURRENCY_UNIT,
        state_class=SensorStateClass.TOTAL,
        reset_period="month",
        icon="mdi:water-boiler",
        entity_registry_enabled_default=True,
        value_fn=lambda d: round(d.month.immersion_savings, 4),
    ),
    GivEnergyManagerSensorDescription(
        key="self_sufficiency_this_month",
        translation_key="self_sufficiency_this_month",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:home-battery",
        entity_registry_enabled_default=True,
        value_fn=lambda d: round(d.month.self_sufficiency_pct, 1),
    ),
    GivEnergyManagerSensorDescription(
        key="cheap_import_fraction_this_month",
        translation_key="cheap_import_fraction_this_month",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:chart-pie",
        entity_registry_enabled_default=False,
        value_fn=lambda d: values.cheap_import_percentage(d.month),
    ),
    GivEnergyManagerSensorDescription(
        key="battery_roundtrip_efficiency_today",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="battery_roundtrip_efficiency_today",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-sync",
        entity_registry_enabled_default=False,
        value_fn=values.battery_roundtrip_efficiency_today,
    ),
    GivEnergyManagerSensorDescription(
        key="net_position_this_month",
        translation_key="net_position_this_month",
        native_unit_of_measurement=CURRENCY_UNIT,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        reset_period="month",
        icon="mdi:scale-balance",
        entity_registry_enabled_default=False,
        value_fn=lambda d: round(d.month.net_position, 4),
    ),
)
