"""Today by rate tier, with savings, battery throughput and solar capture."""

from __future__ import annotations

from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.const import PERCENTAGE, EntityCategory, UnitOfEnergy

from .. import sensor_values as values
from ..core.devices import Device
from .base import CURRENCY_UNIT, GivEnergyManagerSensorDescription

DESCRIPTIONS: tuple[GivEnergyManagerSensorDescription, ...] = (
    # ── Today — rate-tier breakdown and savings ───────────────────────────────
    GivEnergyManagerSensorDescription(
        key="import_kwh_cheap_today",
        translation_key="import_kwh_cheap_today",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        icon="mdi:lightning-bolt-circle",
        is_daily_total=True,
        value_fn=lambda d: round(d.today.import_kwh_cheap, 3),
    ),
    GivEnergyManagerSensorDescription(
        key="import_kwh_peak_today",
        translation_key="import_kwh_peak_today",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        icon="mdi:lightning-bolt",
        is_daily_total=True,
        value_fn=lambda d: round(d.today.import_kwh_peak, 3),
    ),
    GivEnergyManagerSensorDescription(
        key="import_cost_cheap_today",
        translation_key="import_cost_cheap_today",
        native_unit_of_measurement=CURRENCY_UNIT,
        state_class=SensorStateClass.TOTAL,
        icon="mdi:cash-minus",
        is_daily_total=True,
        value_fn=lambda d: round(d.today.import_cost_cheap, 4),
    ),
    GivEnergyManagerSensorDescription(
        key="import_cost_peak_today",
        translation_key="import_cost_peak_today",
        native_unit_of_measurement=CURRENCY_UNIT,
        state_class=SensorStateClass.TOTAL,
        icon="mdi:cash",
        is_daily_total=True,
        value_fn=lambda d: round(d.today.import_cost_peak, 4),
    ),
    GivEnergyManagerSensorDescription(
        key="peak_import_fraction_today",
        translation_key="peak_import_fraction_today",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:chart-pie",
        value_fn=lambda d: round(d.today.peak_import_fraction * 100, 1),
    ),
    GivEnergyManagerSensorDescription(
        key="avg_import_rate_today",
        translation_key="avg_import_rate_today",
        native_unit_of_measurement=CURRENCY_UNIT,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:cash-clock",
        entity_registry_enabled_default=False,
        value_fn=lambda d: values.average_import_rate(d.today),
    ),
    GivEnergyManagerSensorDescription(
        key="avg_import_rate_this_week",
        translation_key="avg_import_rate_this_week",
        native_unit_of_measurement=CURRENCY_UNIT,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:cash-clock",
        entity_registry_enabled_default=False,
        value_fn=lambda d: values.average_import_rate(d.week),
    ),
    GivEnergyManagerSensorDescription(
        key="avg_import_rate_this_month",
        translation_key="avg_import_rate_this_month",
        native_unit_of_measurement=CURRENCY_UNIT,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:cash-clock",
        entity_registry_enabled_default=False,
        value_fn=lambda d: values.average_import_rate(d.month),
    ),
    GivEnergyManagerSensorDescription(
        key="immersion_savings_today",
        requires=Device.IMMERSION_SWITCH,
        translation_key="immersion_savings_today",
        native_unit_of_measurement=CURRENCY_UNIT,
        state_class=SensorStateClass.TOTAL,
        icon="mdi:water-boiler",
        is_daily_total=True,
        value_fn=lambda d: round(d.today.immersion_savings, 4),
    ),
    GivEnergyManagerSensorDescription(
        key="immersion_solar_kwh_today",
        requires=Device.IMMERSION_SWITCH,
        translation_key="immersion_solar_kwh_today",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        icon="mdi:water-boiler-auto",
        is_daily_total=True,
        value_fn=lambda d: round(d.today.immersion_solar_kwh, 3),
    ),
    GivEnergyManagerSensorDescription(
        key="battery_throughput_kwh_today",
        translation_key="battery_throughput_kwh_today",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        icon="mdi:battery-sync",
        is_daily_total=True,
        value_fn=lambda d: round(d.today.battery_throughput_kwh, 3),
    ),
    GivEnergyManagerSensorDescription(
        key="battery_throughput_budget_pct",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="battery_throughput_budget_pct",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-sync",
        entity_registry_enabled_default=False,
        value_fn=values.battery_throughput_budget_pct,
    ),
    GivEnergyManagerSensorDescription(
        key="battery_throughput_budget_status",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="battery_throughput_budget_status",
        icon="mdi:battery-heart-variant",
        entity_registry_enabled_default=False,
        value_fn=lambda d: d.battery_throughput_budget_status or None,
    ),
    GivEnergyManagerSensorDescription(
        key="battery_charge_kwh_today",
        translation_key="battery_charge_kwh_today",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        icon="mdi:battery-arrow-up",
        is_daily_total=True,
        entity_registry_enabled_default=False,
        value_fn=lambda d: round(d.today.battery_charge_kwh, 3),
    ),
    GivEnergyManagerSensorDescription(
        key="battery_discharge_kwh_today",
        translation_key="battery_discharge_kwh_today",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        icon="mdi:battery-arrow-down-outline",
        is_daily_total=True,
        entity_registry_enabled_default=False,
        value_fn=lambda d: round(d.today.battery_discharge_kwh, 3),
    ),
    GivEnergyManagerSensorDescription(
        key="house_kwh_today",
        translation_key="house_kwh_today",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        icon="mdi:home-lightning-bolt",
        is_daily_total=True,
        value_fn=lambda d: round(d.today.house_kwh, 3),
    ),
    GivEnergyManagerSensorDescription(
        key="missed_solar_today",
        translation_key="missed_solar_today",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        is_daily_total=True,
        entity_registry_enabled_default=False,
        value_fn=lambda d: round(d.today.missed_solar_kwh, 3),
    ),
    GivEnergyManagerSensorDescription(
        key="solar_capture_efficiency_today",
        translation_key="solar_capture_efficiency_today",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:solar-power-variant",
        entity_registry_enabled_default=False,
        value_fn=values.solar_capture_efficiency_today,
    ),
)
