"""
Keeps docs/sensors.md in step with sensor.py.

docs/sensors.md is generated by scripts/gen_sensor_docs.py. These tests run the
generator and compare its output with the committed page, so a sensor that is
added, renamed or changed without regenerating the docs fails the suite.

Fix a failure with: python scripts/gen_sensor_docs.py
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

_ROOT = Path(__file__).parent.parent
_SCRIPT = _ROOT / "scripts" / "gen_sensor_docs.py"
_DOC = _ROOT / "docs" / "sensors.md"


@pytest.fixture(scope="module")
def generator():
    spec = importlib.util.spec_from_file_location("gen_sensor_docs", _SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_sensors_page_is_up_to_date(generator):
    expected = generator.generate()
    actual = _DOC.read_text(encoding="utf-8")
    assert actual == expected, (
        "docs/sensors.md is out of date against sensor.py. "
        "Run: python scripts/gen_sensor_docs.py"
    )


def test_every_sensor_key_is_listed(generator):
    page = _DOC.read_text(encoding="utf-8")
    missing = [s["key"] for s in generator.load_sensors() if f"`{s['key']}`" not in page]
    assert missing == []


def test_no_sensor_falls_into_other_group(generator):
    other = [s["key"] for s in generator.load_sensors() if generator.group_of(s["key"]) == "Other"]
    assert other == [], f"add these keys to a group in gen_sensor_docs.py: {other}"


def test_every_sensor_has_a_description_or_is_a_period_sensor(generator):
    period_suffixes = tuple(suffix for suffix, _ in generator.SUFFIX_GROUPS)
    undocumented = [
        s["key"]
        for s in generator.load_sensors()
        if s["key"] not in generator.DESCRIPTIONS and not s["key"].endswith(period_suffixes)
    ]
    assert undocumented == [], f"add a DESCRIPTIONS entry for: {undocumented}"


def test_check_flag_passes_on_the_committed_page(generator, capsys):
    assert generator.main(["--check"]) == 0
    assert capsys.readouterr().err == ""
