"""
render.py - turns the views into the YAML text of the dashboard file, or into a dict.

_generate is the one place a dashboard is built. The YAML file and the Lovelace strategy
both call it.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import yaml
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant

from ..const import DOMAIN, SERVICE_GET_DASHBOARD_YAML
from .hacs import HACS_CARDS, HacsCard, HacsCards, async_lovelace_resource_urls
from .registry import HostFacts, async_admin_user_ids
from .views import TAB_VIEWS, Builder

# ── YAML ─────────────────────────────────────────────────────────────────────


class _DashboardDumper(yaml.SafeDumper):
    """SafeDumper that writes multi-line strings as literal blocks and never folds."""

    def ignore_aliases(self, data):
        return True


def _represent_str(dumper: yaml.SafeDumper, data: str):
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


_DashboardDumper.add_representer(str, _represent_str)


def _dump_yaml(data: dict) -> str:
    """Serialise with the options Home Assistant uses for its own YAML output."""
    return yaml.dump(
        data,
        Dumper=_DashboardDumper,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
        width=10_000,
    )


# ── Rendering ────────────────────────────────────────────────────────────────

_HEADER_TITLE = f"""\
# GivEnergy Inverter Manager — Generated Dashboard
# Generated by: Developer Tools → Actions → {DOMAIN}.{SERVICE_GET_DASHBOARD_YAML}
#
"""
_HEADER_USE = """\
# All other views use only built-in HA cards.
#
# To use: Settings → Dashboards → new blank dashboard
#         Three-dot menu → Edit dashboard → Raw configuration editor → paste
"""


@dataclass
class _Built:
    config: dict
    skipped: list[str] = field(default_factory=list)
    cards: HacsCards = field(default_factory=lambda: HacsCards(None))


def render_dashboard(
    hass: HomeAssistant,
    entry: ConfigEntry,
    facts: HostFacts,
    registry=None,
) -> tuple[str, list[str]]:
    """Return the dashboard YAML text and the names of disabled sensors it left out.

    *facts* is what Home Assistant says about the Lovelace resources and the administrators.
    *registry* answers the two entity registry calls the builder makes. It defaults to the
    registry of *hass*.
    """
    built = _generate(hass, entry, facts, registry)
    return _header(built) + _dump_yaml(built.config), built.skipped


def build_dashboard(
    hass: HomeAssistant,
    entry: ConfigEntry,
    facts: HostFacts,
    registry=None,
) -> dict:
    """Return the dashboard as a dict, for the Lovelace strategy."""
    return _generate(hass, entry, facts, registry).config


async def async_host_facts(hass: HomeAssistant) -> HostFacts:
    """Read the Lovelace resources and the administrators the generator needs.

    The administrators are read now, so a role change shows once the dashboard is generated
    again: press Refresh Dashboard, or reload the page of a strategy dashboard.
    """
    return HostFacts(await async_lovelace_resource_urls(hass), await async_admin_user_ids(hass))


def _fallback_note(cards: list[HacsCard]) -> str:
    """The header lines that name the HACS cards the dashboard does without."""
    if not cards:
        return ""
    return (
        "# Built-in cards are used in place of these HACS cards, which are not installed.\n"
        "# Install them from HACS, then generate this file again:\n"
        + "".join(f"#   {card.note}\n" for card in cards)
    )


def _skipped_note(names: list[str]) -> str:
    """The header lines that name the disabled sensors the dashboard leaves out."""
    if not names:
        return ""
    return (
        "# Left out because these sensors are disabled. Enable them in\n"
        "# Settings → Devices & services → Entities, then generate this file again:\n"
        + "".join(f"#   {name}\n" for name in names)
    )


def _header(built: _Built) -> str:
    """The comment at the top of the generated file."""
    used = [card.header for card in HACS_CARDS if card in built.cards.used]
    head = _HEADER_TITLE + "".join(used) + _HEADER_USE
    notes = [_fallback_note(built.cards.fallbacks), _skipped_note(built.skipped)]
    if not any(notes):
        return head + "\n"
    return head + "".join(f"{note}\n" for note in notes if note)


def _generate(
    hass: HomeAssistant,
    entry: ConfigEntry,
    facts: HostFacts,
    registry=None,
) -> _Built:
    """Build the Lovelace configuration as a dict.

    Uses actual entity IDs from the entity registry so names customised in the HA
    UI are respected. A tile or card appears only when its entity is registered and
    enabled, and the feature behind it (EV charger, immersion heater, inverter
    temperature, solar forecast) is configured.
    """
    builder = Builder(hass, entry, facts, registry)
    subviews = builder.build_subviews()
    tabs = [spec.build(builder) for spec in TAB_VIEWS]
    views = [view for view in tabs + subviews if view["sections"]]
    return _Built({"views": views}, sorted(builder.reg.disabled.values()), builder.cards)
